### ISSUE TITLE
[Mod]: Color Presets

### ISSUE THREAD

**Issue by Theren03** [KSP-CKAN/KSP2-NetKAN#132]
### Mod Name

Color Presets

### Author(s)

VChristof

### License

MIT

### Homepage link

- https://forum.kerbalspaceprogram.com/topic/214821-color-presets/
- https://spacedock.info/mod/3317/Color%20presets
- https://github.com/VChristof/ColorPresets

### Download link

- https://github.com/VChristof/ColorPresets
- https://spacedock.info/mod/3317/Color%20presets

**Comment by HebaruSan** [comment]
Hi @VChristof, there's some interest in adding your Color Presets mod to CKAN. Would it be OK with you if we did that? We only add mods to CKAN if the authors are OK with it.

**Comment by VChristof** [comment]
Hi, sure, go ahead. (I have not checked in a while, so it's possible it is
not working properly with the new update)

Regards,
Kristóf

HebaruSan ***@***.***> ezt írta (időpont: 2024. jan. 5., P,
1:46):
