### ISSUE TITLE
[Bug]: SpaceWarp does not extract the BepInEx/patchers directory

### ISSUE THREAD

**Issue by arthomnix** [KSP-CKAN/KSP2-NetKAN#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.32.0

### KSP Version

KSP2 0.1.1.0

### Did you make manual changes?

Yes

### Describe the bug

The metadata for SpaceWarp was designed for older versions of SpaceWarp, and does not extract the BepInEx/patchers directory. It also depends on BepInEx despite SpaceWarp now including BepInEx. This results in KSP2 not being able to start as it cannot find the SpaceWarp patcher.

see also: https://github.com/KSP-CKAN/KSP2-NetKAN/pull/15

Old:

- <https://spacedock.info/mod/3255/BepInEx%20for%20KSP%202>

New:

- <https://spacedock.info/mod/3277/Space%20Warp%20+%20BepInEx>

### Steps to reproduce

* Install SpaceWarp via CKAN
* Launch KSP2
* Game cannot start correctly

**Comment by HebaruSan** [comment]
Thanks for the report! ❤️ 
FYI, I have an unrelated fire to put out in some of the back-end Python code right now (mods submitted from SpaceDock with co-authors throw exceptions), but I'll come back to this after that is resolved.

**Comment by arthomnix** [comment]
(carrying on from #15) It doesn't really look like the BepInEx for KSP2 spacedock page is being maintained anymore (it still hasn't been updated to say it supports 0.1.1.0), and SpaceWarp packages BepInEx now, so could we just get rid of standalone BepInEx entirely (or set it as `replaced-by` SpaceWarp)?

**Comment by cheese3660** [comment]
A note on SpaceWarp's provision of BepInEx, SpaceWarp also provides a patched configuration for BepInEx that is necessary for KSP2 that was not provided in the old BepInEx pacakge
