### ISSUE TITLE
Update metadata for UITKforKSP2

### ISSUE THREAD

**Issue by Exynom** [KSP-CKAN/KSP2-NetKAN#62]
As title says, uitk 1.3.0 was released on June 11 (see [here](https://github.com/jan-bures/UitkForKsp2/releases/latest)), but kwp2-ckan-meta only reflects the 1.2.0 version from June 1st (see [here](https://github.com/KSP-CKAN/KSP2-CKAN-meta/tree/main/UITKforKSP2)). 

As this is a prerequisite for SpaceWarp it blocks all other mods on 1.3.0 :)

Thanks! :)

**Comment by HebaruSan** [comment]
The latest release of that mod has an inflation error:

![image](https://github.com/KSP-CKAN/KSP2-NetKAN/assets/1559108/e9835c47-047d-4e7e-9f4d-779fa74f0171)

For that to get fixed, either the swinfo file has to be updated to fix the `version_check` property, or the URL that it currently points to has to exist:

- <https://raw.githubusercontent.com/jan-bures/UitkForKsp2/plugin_template/swinfo.json>

**Comment by HebaruSan** [comment]
The file in the repo was fixed 2 weeks ago, so all that remains now is for a new release to be made that contains that update:

- <https://github.com/jan-bures/UitkForKsp2/commit/7743e25a5201c62532cb69816588925af140585f>

**Comment by jan-bures** [comment]
> The file in the repo was fixed 2 weeks ago, so all that remains now is for a new release to be made that contains that update:
> 
> * [jan-bures/UitkForKsp2@7743e25](https://github.com/jan-bures/UitkForKsp2/commit/7743e25a5201c62532cb69816588925af140585f)

Fixed in 1.4.0, sorry for the delay

**Comment by HebaruSan** [comment]
Awesome! That version should be rolling out to users in a few minutes:

<https://github.com/KSP-CKAN/KSP2-CKAN-meta/commit/21e0b234b2218834f92452bf3b1d22032e0e693b>

**Comment by Exynom** [comment]
great, thanks for the super quick fix! :) 🎉
